package com.xetax.crm.whatsapp.dto;

import lombok.Data;

import java.util.List;

/**
 * A new message template to submit to Meta for approval.
 *
 * <p>MARKETING / UTILITY: headerText/bodyText/footerText are used; bodyText
 * may contain {{1}}, {{2}} variables and exampleParams must then supply one
 * sample value per variable (Meta rejects templates without examples).
 *
 * <p>AUTHENTICATION: Meta mandates a fixed OTP structure — body/footer text
 * are generated by Meta, so only name + language are used from this request.
 */
@Data
public class TemplateCreateRequest {
    private String name;
    /** MARKETING | UTILITY | AUTHENTICATION */
    private String category;
    private String language = "en";
    private String headerText;
    private String bodyText;
    private String footerText;
    private List<String> exampleParams;
}
