package com.xetax.crm.whatsapp.dto;

import lombok.Data;

import java.util.List;

/**
 * A new message template to submit to Meta for approval.
 *
 * <p>MARKETING / UTILITY: headerText/bodyText/footerText are used; bodyText
 * may contain {{1}}, {{2}} variables and exampleParams must then supply one
 * sample value per variable (Meta rejects templates without examples).
 *
 * <p>AUTHENTICATION: Meta mandates a fixed OTP structure — body/footer text
 * are generated by Meta, so only name + language are used from this request.
 */
@Data
public class TemplateCreateRequest {
    private String name;
    /** MARKETING | UTILITY | AUTHENTICATION */
    private String category;
    private String language = "en";
    /** TEXT (default) | IMAGE | VIDEO | DOCUMENT | NONE */
    private String headerFormat;
    private String headerText;
    /** Sample value for a {{1}} in headerText — Meta rejects a header variable without one. */
    private String headerExample;
    /**
     * Media header only: the handle returned by the sample upload endpoint.
     * Meta wants a real example of the media a reviewer will see.
     */
    private String headerHandle;
    /**
     * Media header only: the image/video/document every send of this template
     * will carry. Stored with the template so a campaign does not have to
     * repeat it on every message.
     */
    private String headerMediaUrl;
    private String bodyText;
    private String footerText;
    private List<String> exampleParams;
    private List<TemplateButton> buttons;
    /** MARKETING carousel cards. Present only for a carousel template. */
    private List<TemplateCard> cards;
}
